// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package br.edu.ifce.postit.server.controller;

public final class UserControllerImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void createUser(br.edu.ifce.postit.server.model.User)"),
	new java.rmi.server.Operation("void deleteUser(br.edu.ifce.postit.server.model.User)"),
	new java.rmi.server.Operation("br.edu.ifce.postit.server.model.User findUserById(int)"),
	new java.rmi.server.Operation("br.edu.ifce.postit.server.model.User findUserByLoginAndPassword(java.lang.String, java.lang.String)"),
	new java.rmi.server.Operation("java.util.List listUsers()"),
	new java.rmi.server.Operation("boolean login(java.lang.String, java.lang.String)")
    };
    
    private static final long interfaceHash = -7603939591515341775L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (opnum < 0) {
	    if (hash == -6224210531336210335L) {
		opnum = 0;
	    } else if (hash == -4577516996290843684L) {
		opnum = 1;
	    } else if (hash == 3891365954115048315L) {
		opnum = 2;
	    } else if (hash == 762351086782683544L) {
		opnum = 3;
	    } else if (hash == -8646650037484570140L) {
		opnum = 4;
	    } else if (hash == -3488153054972647034L) {
		opnum = 5;
	    } else {
		throw new java.rmi.UnmarshalException("invalid method hash");
	    }
	} else {
	    if (hash != interfaceHash)
		throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	}
	
	br.edu.ifce.postit.server.controller.UserControllerImpl server = (br.edu.ifce.postit.server.controller.UserControllerImpl) obj;
	switch (opnum) {
	case 0: // createUser(User)
	{
	    br.edu.ifce.postit.server.model.User $param_User_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_User_1 = (br.edu.ifce.postit.server.model.User) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    server.createUser($param_User_1);
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // deleteUser(User)
	{
	    br.edu.ifce.postit.server.model.User $param_User_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_User_1 = (br.edu.ifce.postit.server.model.User) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    server.deleteUser($param_User_1);
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 2: // findUserById(int)
	{
	    int $param_int_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_int_1 = in.readInt();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    br.edu.ifce.postit.server.model.User $result = server.findUserById($param_int_1);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 3: // findUserByLoginAndPassword(String, String)
	{
	    java.lang.String $param_String_1;
	    java.lang.String $param_String_2;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_String_1 = (java.lang.String) in.readObject();
		$param_String_2 = (java.lang.String) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    br.edu.ifce.postit.server.model.User $result = server.findUserByLoginAndPassword($param_String_1, $param_String_2);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 4: // listUsers()
	{
	    call.releaseInputStream();
	    java.util.List $result = server.listUsers();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 5: // login(String, String)
	{
	    java.lang.String $param_String_1;
	    java.lang.String $param_String_2;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_String_1 = (java.lang.String) in.readObject();
		$param_String_2 = (java.lang.String) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    boolean $result = server.login($param_String_1, $param_String_2);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeBoolean($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
